<?php
$array_2 = [];
$array_2['ar']['header.search-here'] = 'ابحث هنا...';

$array_2['ar']['menu.main'] = 'الرئيسية';
$array_2['ar']['menu.dashboard'] = 'لوحة التحكم';
$array_2['ar']['menu.classes-management'] = 'إدارة الفصول';
$array_2['ar']['menu.candidates'] = 'مرشحين';
$array_2['ar']['menu.classes'] = 'الفصول';
$array_2['ar']['menu.courses-management'] = 'إدارة الدورات';
$array_2['ar']['menu.courses'] = 'الدورات';
$array_2['ar']['menu.exams-management'] = 'إدارة الامتحانات';
$array_2['ar']['menu.exams'] = 'الامتحانات';
$array_2['ar']['menu.calendar'] = 'تقويم';


/* Course */
$array_2['ar']['course.id'] = 'الرقم التعريفي';
$array_2['ar']['course.name'] = 'الأسم';
$array_2['ar']['course.number-question'] = 'عدد الأسئلة';
$array_2['ar']['course.last-started-exam'] = 'بدأ الاختبار الأخير';
$array_2['ar']['course.actions'] = 'إجراءات';
$array_2['ar']['course.edit'] = 'تعديل';
$array_2['ar']['course.delete'] = 'حدف';
$array_2['ar']['course.create-exam'] = 'أنشئ اختبارًا';
$array_2['ar']['course.list-courses'] = 'قائمة الدورات';
$array_2['ar']['course.create'] = 'إنشاء';
$array_2['ar']['course.create-course-dialog'] = 'نافدة إنشاء الدرس';
$array_2['ar']['course.update-course-dialog'] = 'نافدة تحديث الدرس';
$array_2['ar']['course.close'] = 'أغلق';
$array_2['ar']['course.create-course'] = 'أنشئ درس';
$array_2['ar']['course.name-field-required'] = '!الإسم ضروري';
$array_2['ar']['course.could-not-update-this-course'] = 'لا يمكن تحديث هدا الدرس';
$array_2['ar']['course.could-not-create-this-course'] = 'لا يمكن إنشاء هدا الدرس';
$array_2['ar']['course.update-course-success'] = 'تم تحديث الدرس بنجاح';
$array_2['ar']['course.create-course-success'] = 'تم إنشاء الدرس بنجاح';
$array_2['ar']['course.all-field-required'] = 'جميع الخانات ضرورية!';
$array_2['ar']['course.course-not-found'] = 'درس غير موجود';
$array_2['ar']['course.delete-course-success'] = 'تم مسح الدرس بنجاح';
$array_2['ar']['course.wait-course-creating'] = '...انتظر الدرس في طور الإنشاء';
$array_2['ar']['course.wait-course-updating'] = '...انتظر الدرس في طور المعالجة';
$array_2['ar']['course.wait-data-course-loading'] = 'انتظر تحميل بيانات الدورة';
$array_2['ar']['course.update-course'] = 'تحديت الدرس';
$array_2['ar']['course.alert-message'] = ' رسالة تنبيه';
$array_2['ar']['course.are-you-sure-you-went-delete-that'] = 'هل تريد فعلا مسحه';
$array_2['ar']['course.yes-delete-it'] = 'نعم,أريد مسحه';
$array_2['ar']['course.no-cancel'] = 'لا,إلغاء';


/* Classe */
$array_2['ar']['classe.id'] = 'الرقم التعريفي';
$array_2['ar']['classe.name'] = 'الإسم';
$array_2['ar']['classe.year'] = 'السنة';
$array_2['ar']['classe.code'] = 'رمز';
$array_2['ar']['classe.avg-note'] = 'معدل القسم';
$array_2['ar']['classe.total-candidat'] = 'مجموع الطلاب';
$array_2['ar']['classe.top-1'] = 'الطالب المتميز';
$array_2['ar']['classe.number-question'] = 'عدد الأسئلة';
$array_2['ar']['classe.last-started-exam'] = 'بدأ الإختبار الأخير';
$array_2['ar']['classe.actions'] = 'إجراءات';
$array_2['ar']['classe.edit'] = 'تعديل';
$array_2['ar']['classe.delete'] = 'حدف';
$array_2['ar']['classe.import-candidat'] = 'ستيراد الطلاب';
$array_2['ar']['classe.code-already-exists'] = 'رمز هذا القسم موجود سابقا';
$array_2['ar']['classe.year-is-not-number'] = 'السنة يجب أن تكون عبارة عن أعداد';
$array_2['ar']['classe.list-classes'] = 'لائحة الأقسام';
$array_2['ar']['classe.create'] = 'إنشاء';
$array_2['ar']['classe.create-classe-dialog'] = 'نافدة إنشاء قسم';
$array_2['ar']['classe.update-classe-dialog'] = 'نافدة تحديث قسم';
$array_2['ar']['classe.close'] = 'حدف';
$array_2['ar']['classe.create-classe'] = 'إنشاء قسم';
$array_2['ar']['classe.name-field-required'] = '!الإسم ضروري';
$array_2['ar']['classe.could-not-update-this-classe'] = 'لا يمكن تحديث هدا القسم';
$array_2['ar']['classe.could-not-create-this-classe'] = 'لا يمكن إنشاءهدا القسم';
$array_2['ar']['classe.update-classe-success'] = 'تم تحديث القسم بنجاح';
$array_2['ar']['classe.create-classe-success'] = 'تم إنشاء القسم بنجاح';
$array_2['ar']['classe.all-field-required'] = '!جميع الخانات ضرورية';
$array_2['ar']['classe.classe-not-found'] = 'قسم غير موجود';
$array_2['ar']['classe.delete-classe-success'] = 'تم حدف القسم بنجاح';
$array_2['ar']['classe.wait-classe-creating'] = '...انتظر قسم في طور الإنشاء';
$array_2['ar']['classe.wait-classe-updating'] = '...انتظر قسم في طور المعالجة';
$array_2['ar']['classe.wait-data-classe-loading'] = 'انتظر تحميل بيانات القسم';
$array_2['ar']['classe.update-classe'] = 'تحديث القسم';
$array_2['ar']['classe.alert-message'] = 'رسالة تنبيه';
$array_2['ar']['classe.are-you-sure-you-went-delete-that'] = '!هل تريد فعلا مسحه';
$array_2['ar']['classe.yes-delete-it'] = 'نعم,أريد مسحه';
$array_2['ar']['classe.no-cancel'] = '!لا,إلغاء';


/* Candidat */
$array_2['ar']['candidat.list-candidates'] = 'قائمة الطلاب';
$array_2['ar']['candidat.id'] = 'الرقم التعريفي';
$array_2['ar']['candidat.id-candidat'] = 'الرقم التعريفي للطالب';
$array_2['ar']['candidat.id-classe'] = 'الرقم التعريفي للقسم';
$array_2['ar']['candidat.first-name'] = 'الاسم الشخصي';
$array_2['ar']['candidat.last-name'] = 'اسم العائلي';
$array_2['ar']['candidat.email'] = ' البريد الإلكتروني';
$array_2['ar']['candidat.class-name'] = "اسم القسم";
$array_2['ar']['candidat.class'] = 'القسم';
$array_2['ar']['candidat.year'] = 'السنة';
$array_2['ar']['candidat.actions'] = 'الإجراءات';
$array_2['ar']['candidat.create'] = 'إنشاء';
$array_2['ar']['candidat.edit'] = 'تعديل';
$array_2['ar']['candidat.delete'] = 'حذف';
$array_2['ar']['candidat.alert-message'] = '!رسالة تنبيه';
$array_2['ar']['candidat.are-you-sure-you-went-delete-that'] = 'هل تريد فعلا مسحه!';
$array_2['ar']['candidat.yes-delete-it'] = 'نعم,أريد مسحه!';
$array_2['ar']['candidat.no-cancel'] = '!لا ، إلغاء';
$array_2['ar']['candidat.create-candidat-dialog'] = "نافدة إنشاء الطالب";
$array_2['ar']['candidat.update-candidat-dialog'] = 'نافدة تحديث الطالب';
$array_2['ar']['candidat.wait-data-candidat-loading'] = 'انتظر تحميل بيانات الطالب';
$array_2['ar']['candidat.wait-candidat-create'] = '...انتظر الطالب في طور التسجيل!';
$array_2['ar']['candidat.wait-candidat-updating'] = '...انتظر تحديث الطالب ';
$array_2['ar']['candidat.close'] = 'إغلاق';
$array_2['ar']['candidat.create-candidat'] = 'إضافة طالب';
$array_2['ar']['candidat.update-candidat'] = 'تحديث طالب';
$array_2['ar']['candidat.The-Format-Of-Id-Classe-Should-Be-Array'] = '!الرقم التعريفي للقسم يجب أن يكون على شكل جدول';
$array_2['ar']['candidat.verify-id-classe'] = ' يجب التحقق من الرقم التعريفي للقسم';
$array_2['ar']['candidat.email-already-exists-for-this-class'] = '!البريد الإلكتروني موجود سابقا لهذا القسم';
$array_2['ar']['candidat.create-candidat-success'] = 'تم إنشاء المرشح بنجاح';
$array_2['ar']['candidat.all-field-required'] = 'جميع الخانات ضرورية';
$array_2['ar']['candidat.candidat-not-found'] = '!لم يتم العثور على الطالب';
$array_2['ar']['candidat.email-already-exists-for-other-candidat'] = '!البريد الإلكتروني موجود  لطالب آخر';
$array_2['ar']['candidat.update-candidat-success'] = 'تم تحديث الطالب بنجاح';
$array_2['ar']['candidat.delete-candidat-success'] = 'تم حدف الطالب بنجاح';

$array_1 = [];
$array_1['ar'] = [
    'candidat.actions' => 'الإجراءات',
    'candidat.alert-message' => 'رسالة تنبيه!',
    'candidat.all-field-required' => 'كل الحقول مطلوبة!',
    'candidat.are-you-sure-you-gone-delete-that' => 'هل أنت متأكد من أنك ذهبت لحذف ذلك!',
    'candidat.candidat-already-موجود' => '',
    'candidat.candidat-not-found' => 'لم يتم العثور على المرشح!',
    'candidat.class' => 'Class',
    'candidat.class-name' => 'Class name',
    'candidat.close' => 'إغلاق',
    'candidat.could-not-create-class-candidat' => 'لا يمكن إنشاء مرشح فئة',
    'candidat.could-not-create-this-candidat' => 'لا يمكن إنشاء هذا المرشح',
    'candidat.could-not-update-class-candidat' => 'لا يمكن تحديث مرشح الفئة',
    'candidat.could-not-update-information-candidat' => 'لا يمكن تحديث مرشح المعلومات',
    'candidat.create' => 'إنشاء',
    'Candidat.create-candidat' => 'أنشئ مرشحًا',
    'candidat.create-candidat -oir' => 'أنشئ حوارًا ترشيحيًا!',
    'Candat.create-candidat-Success' => 'أنشئ نجاحًا مرشحًا',
    'candidat.delete' => 'حذف',
    'candidat.delete-candidat-Success' => 'احذف نجاح المرشح!',
    'candidat.edit' => 'تحرير',
    'candidat.email' => 'Email',
    'candidat.email-already-exists-for-other-candidat' => 'البريد الإلكتروني موجود بالفعل لمرشح آخر!',
    'candidat.email-already-exists-for-this-class' => 'البريد الإلكتروني موجود بالفعل لهذه الفئة!',
    'candidat.email-must-be-valide' => 'يجب أن يكون البريد الإلكتروني Valide',
    'candidat.file-name' => 'اسم الملف',
    'candidat.file-not-exists' => 'الملف غير موجود',
    'candidat.filter' => 'مرشح',
    'candidat.filter-candidat' => 'تصفية المرشح',
    'Candat.filter-candidat -اور' => 'تصفية حوار المرشح',
    'candidat.first-name' => 'First Name',
    'candidat.id' => 'ID',
    'Candidat.id-candidat' => 'Id Candidat',
    'candidat.id-classe' => 'Id Classe',
    'candidat.id-classe-is-not-array-given' => 'Id classe ليست مصفوفة معطاة',
    'candidat.import' => 'استيراد',
    'candidat.import-candidat' => 'دعم حوار المرشح',
    'candidat.import-candidat-dialog' => 'استيراد حوار ترشيح',
    'Candat.import-candidat-Success' => 'استيراد مرشح نجاح',
    'candidat.last-name' => "اسم العائلة",
    'candidat.list-candidates' => 'قائمة المرشحين',
    'Candat.must-be-valide' => 'must be valide',
    'candidat.no-cancel' => 'لا ; يلغي!',
    'candidat.required' => 'مطلوب',
    'candidat.reset' => 'إعادة تعيين',
    'candidat.update-candidat' => 'تحديث المرشح',
    'candidat.update-candidat -اور في الظهور' => 'تحديث مربع الحوار المرشح!',
    'candidat.update-candidat-Success' => 'تحديث نجاح المرشح!',
    'candidat.verify' => 'تحقق',
    'candidat.verify-id-classe' => 'يجب التحقق من id classe!',
    'candidat.wait-candidat-create' => 'انتظر إنشاء المرشح!',
    'candidat.wait-candidat-upadting' => 'انتظر صريحًا حتى تحديث',
    'candidat.wait-data-candidat-loading' => 'انتظر مرشح البيانات للتحميل!',
    'candidat.year' => 'Year',
    'candidat.yes-delete-it' => 'نعم ; احذفه!',
    'classe.actions' => 'الإجراءات',
    'classe.alert-message' => 'رسالة تنبيه!',
    'classe.all-field-required' => 'كل الحقول مطلوبة!',
    'classe.are-you-sure-you-gone-delete-that' => 'هل أنت متأكد من حذف ذلك!',
    'classe.avg-note' => "ملاحظات متوسطة",
    'classe.classe-not-found' => 'لم يتم العثور على القسم',
    'classe.close' => 'إغلاق',
    'classe.code' => 'الرقم',
    'classe.code-already-exists' => 'رمز هذه المجموعة موجود بالفعل',
    'classe.could-not-create-this-classe' => 'تعذر إنشاء هذه الفئة',
    'classe.could-not-update-this-classe' => 'تعذر تحديث هذه الفئة',
    'classe.create' => 'إنشاء',
    'classe.create-classe' => 'إنشاء Classe',
    'classe.create-classe-Dialog' => 'إنشاء حوار Classe',
    'classe.create-classe-Success' => 'حقق Classe النجاح',
    'classe.delete' => 'حذف',
    'classe.delete-classe-Success' => 'Classe تم حذف النجاح',
    'classe.edit' => 'تحرير',
    'classe.id' => 'ID',
    'classe.import-candidat' => 'استيراد مرشح',
    'classe.list-classes' => 'List class',
    'classe.name' => 'الاسم',
    'classe.no-cancell' => 'لا ; يلغي!',
    'classe.top-1' => 'أعلى 1',
    'classe.total-candidat' => 'إجمالي المرشحين',
    'classe.update-classe' => 'تحديث Classe',
    'classe.update-classe-Dialog' => 'تحديث Classe Dialog',
    'classe.update-classe-Success' => 'Classe تم تحديث النجاح',
    'classe.wait-classe-create' => 'انتظر إنشاء classe ...',
    'classe.wait-classe-upadting' => 'انتظر تحديث classe ...',
    'classe.wait-data-classe-loading' => 'انتظر تحميل بيانات classe',
    "classe.year" => "السنة",
    'classe.year-is-not-number ' => "السنة ليست رقمًا",
    'classe.yes-delete-it' => 'نعم ; احذفه!',
    'course.actions' => 'الإجراءات',
    'course.add-question' => 'أضف سؤالاً',
    'course.alert-message' => 'رسالة تنبيه!',
    'course.all-field-required' => 'كل الحقول مطلوبة!',
    'course.are-you-sure-you-gone-delete-that' => 'هل أنت متأكد أنك ذهبت إلى حذف ذلك!',
    'course.change-question-course-success' => 'تغيير مسار دورة السؤال عن النجاح',
    'course.close' => 'إغلاق',
    'course.could-not-create-this-course' => 'تعذر إنشاء هذه الدورة التدريبية',
    'course.could-not-create-this-question' => 'تعذر إنشاء هذا السؤال',
    'course.could-not-update-this-course' => 'لا يمكن تحديث هذه الدورة',
    'course.could-not-update-this-question' => 'تعذر تحديث هذا السؤال',
    'course.course-not-found' => 'الدورة غير موجودة',
    'course.create' => 'إنشاء',
    'course.create-course' => 'إنشاء دورة',
    'course.create-course-dialog' => 'إنشاء مربع حوار حول الدورة التدريبية',
    'course.create-course-success' => "النجاح في إنشاء الدورة التدريبية",
    'course.create-exam' => 'إنشاء اختبار',
    'course.create-question' => 'إنشاء سؤال',
    'course.delete' => 'حذف',
    'course.delete-course-success' => "تم حذف الدورة بنجاح",
    'course.edit' => 'تحرير',
    'course.id' => 'ID',
    'course.last-started-exam' => 'Last Started Exam',
    'course.list-course' => "قائمة الدورات",
    'course.name' => 'Name',
    'course.name-field-required' => 'حقل الاسم مطلوب!',
    'course.no-Cancel' => 'لا ; يلغي!',
    'course.number-question' => 'عدد الأسئلة',
    'course.question-add-option' => 'اضافة خيار اخر',
    'course.question-course-dialog' => 'Question Course Dialog',
    'course.question.delete' => 'حذف الأسئلة',
    'course.question.false' => 'False',
    'course.question.options' => 'خيارات',
    'course.question.title' => 'العنوان',
    'course.question.true' => 'True',
    'course.question.type' => 'Type',
    'course.save-Changes' => 'Save Changes',
    'course.update-course' => 'تحديث الدورة التدريبية',
    'course.update-course-dialog' => 'Update Course Dialog',
    'course.update-course-Success' => "تحديث الدورة بنجاح",
    'course.wait-course-create' => 'انتظر إنشاء الدورة التدريبية ...',
    'course.wait-course-upadting' => 'انتظر تحديث الدورة التدريبية ...',
    'course.wait-data-course-loading' => "انتظر تحميل بيانات الدورة التدريبية",
    'course.yes-delete-it' => 'نعم ; احذفه!',
    'exam-candidat.already-closed' => 'مرشح الامتحان مغلق بالفعل',
    'exam-candidat.not-authorized-to-close-this-exam' => 'غير مصرّح له بإغلاق هذا الاختبار',
    'exam-candidat.not-found' => 'لم يتم العثور على المرشح للاختبار',
    'exam-candidat.not-started-for-closed' => "لم يبدأ المرشح للاختبار للإغلاق",
    'exam.actions' => 'الإجراءات',
    'exam.alert-message' => 'رسالة تنبيه',
    'exam.all-field-required' => 'All Field required',
    'exam.are-you-sure-you-gone-delete-that' => 'هل أنت متأكد من أنك ذهبت لحذف ذلك!',
    'exam.catch-up' => 'اللحاق بالركب',
    'exam.change-order' => 'تغيير الترتيب',
    'exam.choices' => 'اختيارات',
    'exam.class-not-found' => 'الفصل غير موجود',
    'exam.classes' => 'Classes',
    'exam.close' => 'إغلاق',
    'exam.closing' => 'إغلاق',
    'exam.could-not-create-this-exam' => 'تعذر إنشاء هذا الاختبار',
    'exam.could-not-update-this-exam' => 'تعذر تحديث هذا الاختبار',
    'exam.cours' => 'Course',
    'exam.course-not-found' => 'الدورة غير موجودة',
    'exam.create' => 'إنشاء',
    'exam.create-exam' => 'إنشاء اختبار',
    'exam.create-exam-dialog' => 'Exam Dialog',
    'exam.create-exam-success' => "إنشاء الاختبار بنجاح",
    'exam.delete' => 'حذف',
    'exam.delete-exam-success' => "حذف نجاح الاختبار",
    'exam.document-type-not-support' => 'نوع المستند غير مدعوم',
    'exam.duration' => 'Duration',
    'exam.dureation-min' => 'Duration (min)',
    'exam.edit' => 'تحرير',
    'exam.exam-not-found' => 'لم يتم العثور على الاختبار',
    'exam.export.html' => 'تصدير Html',
    'exam.export.pdf' => 'تصدير ملف PDF',
    'exam.export.word' => "تصدير كلمة",
    'exam.field-required' => "تم تقديمه مطلوبًا",
    'exam.info' => 'معلومات',
    'exam.list-exams' => 'List Exams',
    'exam.message-send-Success' => 'إرسال الرسالة بنجاح',
    'exam.nature' => 'الطبيعة',
    'exam.no-cancell' => 'No Cancel',
    'exam.normal' => 'Normal',
    'exam.number-version' => 'إصدار الرقم',
    "exam.offline" => "غير متصل",
    "exam.online" => "عبر الإنترنت",
    'exam.opened' => 'مفتوح',
    'exam.question-Changes' => 'تغيير الأسئلة',
    'exam.question-exam-الحوار' => 'مربع حوار أسئلة الاختبار',
    'exam.questions' => 'أسئلة',
    'exam.send-exam-via-email' => 'أرسل exaم عبر البريد الإلكتروني ,',
    'exam.start-in' => 'ابدأ في',
    'exam.status' => 'الحالة',
    'exam.strict-date' => 'Strict date',
    "exam.type" => "النوع",
    'exam.update-exam' => "تحديث الامتحان",
    "exam.update-exam-الحوار" => "مربع حوار تحديث الاختبار",
    'exam.update-exam-success' => "تحديث نجاح الاختبار",
    'exam.versions' => 'الإصدارات',
    'exam.view-Marks' => 'عرض العلامات',
    'exam.view-question' => 'عرض السؤال',
    "exam.wait-data-exam-loading" => "انتظار تحميل اختبار البيانات",
    'exam.wait-exam-create' => 'انتظار إنشاء الاختبار',
    'exam.wait-exam-upadting' => 'Wait exam upadting',
    'exam.yes-delete-it' => 'نعم احذفها!',
    'header.search-here' => 'ابحث هنا ...',
    "menu.calendar" => "التقويم",
    'menu.candidates' => 'المرشحين',
    'menu.classes' => 'Classes',
    'menu.classes-management' => 'إدارة الفئات',
    'menu.courses' => 'الدورات',
    'menu.courses-management' => 'إدارة الدورات',
    "menu.dashboard" => "لوحة التحكم",
    'menu.exams' => 'الامتحانات',
    'menu.exams-management' => 'إدارة الاختبارات',
    'menu.main' => 'رئيسي',
    'candidat.the-format-of-id-classe-should-be-array' => 'تنسيق Id Classe يجب أن يكون صفيفًا!',
    'candidat.wait-candidat-updating' => 'انتظر تحديث المرشح!',
    'classe.last-started-exam' => 'Last Started Exam',
    'classe.name-field-required' => 'حقل الاسم مطلوب!',
    'classe.number-question' => 'عدد الأسئلة',
    'classe.wait-classe-updating' => 'انتظر تحديث classe ...',
    'course.wait-course-updating' => 'انتظر تحديث الدورة التدريبية ...',
];

$array_3 = array_merge($array_2, $array_1);


foreach ($array_2['ar'] as $key => $value) {
    $array_1['ar'][$key] = $value;
}


echo json_encode($array_1, JSON_UNESCAPED_UNICODE);